### ISSUE TITLE
添加漏洞扫描任务失败

### ISSUE THREAD

**Issue by hjyuan** [jwt1399/Sec-Tools#1]
昨天添加了扫描任务，但是没扫描成功，是我AWVS的问题，然后在AWVS中删除了这个任务，想用Sec-Tools重新添加扫描一下，然后就遇到问题了，一直添加失败，不知道是不是不能添加重复的网址URL，重新添加一个没有添加过的URL成功了。

**Comment by jwt1399** [comment]
是可以添加重复任务的

**Comment by hjyuan** [comment]
请问扫描结果出现这个该怎么解决呀
```
Using the URLconf defined in Sec_Tools.urls, Django tried these URL patterns, in this order:

    admin/
    [name='welcome']
    index [name='index']
    docs [name='docs']
    about [name='about']
    portscan [name='portscan']
    infoleak [name='infoleak']
    webside [name='webside']
    test [name='test']
    testfp [name='testfp']
    navigation [name='navigation']
    fingerprint [name='fingerprint']
    subdomain [name='subdomain']
    login/ [name='login']
    login_out/ [name='login_out']
    register/ [name='register']
    password-reset/
    dir-result/ [name='dir-result']
    dir-search/ [name='dir-search']
    get-target/ [name='get-target']
    vulnscan [name='vulnscan']
    vuln_scan [name='vuln_scan']
    test1 [name='test1']
    get_vuln_rank [name='get_vuln_rank']
    get_vuln_value [name='get_vuln_value']
    Middleware_scan [name='Middleware_scan']
    start_Middleware_scan [name='start_Middleware_scan']
    test2 [name='test2']
    webscan_backend/
    media/(?P<path>.*)$

The current path, vuln_result/bdbcc0ba-55d8-4550-832d-dd2c9ec645e4, didn't match any of these.
```

**Comment by Adam-01** [comment]
> 请问扫描结果出现这个该怎么解决呀
> 
> ```
> Using the URLconf defined in Sec_Tools.urls, Django tried these URL patterns, in this order:
> 
>     admin/
>     [name='welcome']
>     index [name='index']
>     docs [name='docs']
>     about [name='about']
>     portscan [name='portscan']
>     infoleak [name='infoleak']
>     webside [name='webside']
>     test [name='test']
>     testfp [name='testfp']
>     navigation [name='navigation']
>     fingerprint [name='fingerprint']
>     subdomain [name='subdomain']
>     login/ [name='login']
>     login_out/ [name='login_out']
>     register/ [name='register']
>     password-reset/
>     dir-result/ [name='dir-result']
>     dir-search/ [name='dir-search']
>     get-target/ [name='get-target']
>     vulnscan [name='vulnscan']
>     vuln_scan [name='vuln_scan']
>     test1 [name='test1']
>     get_vuln_rank [name='get_vuln_rank']
>     get_vuln_value [name='get_vuln_value']
>     Middleware_scan [name='Middleware_scan']
>     start_Middleware_scan [name='start_Middleware_scan']
>     test2 [name='test2']
>     webscan_backend/
>     media/(?P<path>.*)$
> 
> The current path, vuln_result/bdbcc0ba-55d8-4550-832d-dd2c9ec645e4, didn't match any of these.
> ```

这个path是在vulnscan/urls.py的21行处使用通配符去添加的，您可以在此处调试。我猜测可能是你的AWVS没有正确启动，导致没有获取到target_ids。

**Comment by hjyuan** [comment]
谢谢！刚才又有一个问题，在进行端口扫描时限制字符在15个字符，超过15个字符无法输入，少于15个字符会有提示，但是输入IP（例如192.168.152.129）后显示请输入正确的IP，这个该怎么解决呢，是我的环境问题吗

**Comment by Adam-01** [comment]
> 谢谢！刚才又有一个问题，在进行端口扫描时限制字符在15个字符，超过15个字符无法输入，少于15个字符会有提示，但是输入IP（例如192.168.152.129）后显示请输入正确的IP，这个该怎么解决呢，是我的环境问题吗

考虑到安全问题，这个ip被禁止扫描了，您可以在Sec_Tools\webscan_backend\plugins\common\common.py的FORBIDDEN_IP_RULE(13-18行)更改匹配模式。
