### ISSUE TITLE
提个目录扫描的小建议

### ISSUE THREAD

**Issue by aa506** [jwt1399/Sec-Tools#3]
目录扫描参照dirsearch，但是能不能添加新字典或者url path到默认的字典文件中呢。

**Comment by jwt1399** [comment]
> 目录扫描参照dirsearch，但是能不能添加新字典或者url path到默认的字典文件中呢。

感谢你的建议，这个功能目前版本还不支持

**Comment by xiafeng2333** [comment]
> 目录扫描参照dirsearch，但是能不能添加新字典或者url path到默认的字典文件中呢。

自己魔改一下前端是可以实现的，你看目录扫描的前端代码就明白了
