### ISSUE TITLE
扫描后打不开报告显示404

### ISSUE THREAD

**Issue by xg6666** [jwt1399/Sec-Tools#5]
![image](https://user-images.githubusercontent.com/72715239/156878186-c17fb124-e656-4a56-aac3-dfac0cb4d5c8.png)

**Comment by lay1007zr** [comment]
你好 你解决这个问题了吗

**Comment by lay1007zr** [comment]
> ![图片](https://user-images.githubusercontent.com/72715239/156878186-c17fb124-e656-4a56-aac3-dfac0cb4d5c8.png)

你好 你解决这个问题了吗
